const AUTO_CLASS_RE = /^[A-Z][A-Za-z]+_[a-zA-Z]+__[A-Za-z0-9]{5,}$/; // CSS Modules pattern
const EMOTION_RE = /^css-[a-z0-9]{6,}$/;                             // emotion
const STYLED_RE = /^sc-[a-zA-Z0-9]{5,}$/;                            // styled-components

function isAutoGenerated(cls: string): boolean {
  return AUTO_CLASS_RE.test(cls) || EMOTION_RE.test(cls) || STYLED_RE.test(cls);
}

export function uniqueSelector(el: Element): string {
  if (el.id && document.querySelectorAll(`#${CSS.escape(el.id)}`).length === 1) {
    return `#${CSS.escape(el.id)}`;
  }
  const parts: string[] = [];
  let current: Element | null = el;
  while (current && current !== document.documentElement) {
    parts.unshift(localSelector(current));
    const combined = parts.join(' > ');
    if (document.querySelectorAll(combined).length === 1) return combined;
    current = current.parentElement;
  }
  return parts.join(' > ');
}

function localSelector(el: Element): string {
  const tag = el.tagName.toLowerCase();
  const classes = Array.from(el.classList).filter((c) => !isAutoGenerated(c));
  let base = tag + classes.map((c) => '.' + CSS.escape(c)).join('');
  if (el.parentElement) {
    const siblings = Array.from(el.parentElement.children).filter((c) => c.tagName === el.tagName);
    if (siblings.length > 1) {
      const idx = siblings.indexOf(el) + 1;
      base += `:nth-of-type(${idx})`;
    }
  }
  return base;
}
